In [141]:
import numpy as np

In [142]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [143]:
#Boolean Indexing
a[a%6==0] = 0
print(a,"\n","-"*18)
a[a%4==0] = 0
print(a)

[[ 0  1  2  3  4]
 [ 5  0  7  8  9]
 [10 11  0 13 14]
 [15 16 17  0 19]
 [20 21 22 23  0]] 
 ------------------
[[ 0  1  2  3  0]
 [ 5  0  7  0  9]
 [10 11  0 13 14]
 [15  0 17  0 19]
 [ 0 21 22 23  0]]


In [144]:
a > 0

array([[False,  True,  True,  True, False],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True,  True],
       [ True, False,  True, False,  True],
       [False,  True,  True,  True, False]])

In [145]:
a = np.arange(25).reshape(5,5)
print(a)
a[np.logical_or(a%6==0, a%4==0)] = -1
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[-1,  1,  2,  3, -1],
       [ 5, -1,  7, -1,  9],
       [10, 11, -1, 13, 14],
       [15, -1, 17, -1, 19],
       [-1, 21, 22, 23, -1]])

In [146]:
a = np.arange(0, 25, 2)
print(a)
a[np.logical_and(a%6==0, a%4==0)] = -1
a

[ 0  2  4  6  8 10 12 14 16 18 20 22 24]


array([-1,  2,  4,  6,  8, 10, -1, 14, 16, 18, 20, 22, -1])

In [147]:
a == -1

array([ True, False, False, False, False, False,  True, False, False,
       False, False, False,  True])

In [148]:
M = 10
N = 15
x_min = y_min = 3.0
x_max = y_max = 9.0

x = np.linspace(x_min, x_max, M, endpoint=False)
y = np.linspace(y_min, y_max, N, endpoint=False)

print(x.shape)
print(y.shape)
print(x)
print(y)

(10,)
(15,)
[3.  3.6 4.2 4.8 5.4 6.  6.6 7.2 7.8 8.4]
[3.  3.4 3.8 4.2 4.6 5.  5.4 5.8 6.2 6.6 7.  7.4 7.8 8.2 8.6]


In [149]:
import time

In [150]:
#Slower
t0 = time.time()

g = np.zeros((M, N))

for i in range(M):
    for j in range(N):
        g[i,j] = np.sin(2.0*np.pi*x[i]*y[j])
        
t1 = time.time()
print("Time taken : {}'s".format(t1-t0))

Time taken : 0.0009949207305908203's


In [151]:
#Formation of meshgrid
x2, y2 = np.meshgrid(x, y, indexing="ij")

print(x2[:,0])
print(x2[0,:])

print(y2[:,0])
print(y2[0,:])

[3.  3.6 4.2 4.8 5.4 6.  6.6 7.2 7.8 8.4]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
[3.  3.4 3.8 4.2 4.6 5.  5.4 5.8 6.2 6.6 7.  7.4 7.8 8.2 8.6]


In [152]:
#Faster
t0 = time.time()

new_g = np.sin(2.0*np.pi*x2*y2)

t1 = time.time()
print("Time taken: {}'s".format(t1-t0))

Time taken: 0.0's


In [153]:
#Concatenation
x = np.arange(4)
y = np.arange(4,10)
np.concatenate([x,y])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
#3 arrays concatenation
np.concatenate([x,x[::-1],x])

array([0, 1, 2, 3, 3, 2, 1, 0, 0, 1, 2, 3])

In [155]:
d1 = np.arange(25).reshape(5,5)
d2 = np.arange(15).reshape(3,5)

In [156]:
#concatenate 2D arrays along axis=0(default)
#Row
np.concatenate([d1, d2])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [157]:
#concatenate 2D arrays along axis=1
#Column
np.concatenate([d1, d2.reshape(5,3)], axis=1)

array([[ 0,  1,  2,  3,  4,  0,  1,  2],
       [ 5,  6,  7,  8,  9,  3,  4,  5],
       [10, 11, 12, 13, 14,  6,  7,  8],
       [15, 16, 17, 18, 19,  9, 10, 11],
       [20, 21, 22, 23, 24, 12, 13, 14]])

In [158]:
lst = list(range(0,8))
a, b, c, d = np.split(lst, [2, 4, 6])
print(a, b, c, d)

[0 1] [2 3] [4 5] [6 7]


In [159]:
d1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [160]:
l, r = np.hsplit(d1, [-3])
print(l,"\n"+"-"*12+"\n",r)

[[ 0  1]
 [ 5  6]
 [10 11]
 [15 16]
 [20 21]] 
------------
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]


In [161]:
#Similar to reduce() used in lists
np.add.reduce(x)

6

In [162]:
np.multiply.reduce(x[1:])

6

In [163]:
#For intermediate results
np.add.accumulate(x[::-1])

array([3, 5, 6, 6], dtype=int32)

In [164]:
np.add.accumulate(x)

array([0, 1, 3, 6], dtype=int32)

In [165]:
np.multiply.accumulate(x[:0:-1])

array([3, 6, 6], dtype=int32)