In [1]:
#Importing numpy
import numpy as np

In [2]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
#Reshaping
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
#Printing meta-data
print("Dimensions: ", a.ndim)
print("Shape: ",a.shape)
print("Size: ",a.size)
print("Type: ",a.dtype)
print("Size of item: ",a.itemsize)
print(type(a))

Dimensions:  2
Shape:  (5, 5)
Size:  25
Type:  int32
Size of item:  4
<class 'numpy.ndarray'>


In [5]:
#Numpy array using list
float_array = np.array([21.0, 24.0, 53.0, 73.0])
print(float_array)
print(float_array.dtype)

[21. 24. 53. 73.]
float64


In [6]:
#Identity matrix
c = np.eye(5)
c

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
#Generate evenly spaced numbers between two numbers
lin = np.linspace(5, 6, 10, endpoint=True)
print(lin,"\n","-"*65)
lin = np.linspace(5, 10, 3, endpoint=False)
print(lin)

[5.         5.11111111 5.22222222 5.33333333 5.44444444 5.55555556
 5.66666667 5.77777778 5.88888889 6.        ] 
 -----------------------------------------------------------------
[5.         6.66666667 8.33333333]


In [8]:
#Generate evenly spaced log numbers between two numbers
log = np.logspace(99, 105, 45, endpoint=True, base=10)
print(log)

[1.00000000e+099 1.36887451e+099 1.87381742e+099 2.56502091e+099
 3.51119173e+099 4.80638086e+099 6.57933225e+099 9.00628020e+099
 1.23284674e+100 1.68761248e+100 2.31012970e+100 3.16227766e+100
 4.32876128e+100 5.92553098e+100 8.11130831e+100 1.11033632e+101
 1.51991108e+101 2.08056754e+101 2.84803587e+101 3.89860370e+101
 5.33669923e+101 7.30527154e+101 1.00000000e+102 1.36887451e+102
 1.87381742e+102 2.56502091e+102 3.51119173e+102 4.80638086e+102
 6.57933225e+102 9.00628020e+102 1.23284674e+103 1.68761248e+103
 2.31012970e+103 3.16227766e+103 4.32876128e+103 5.92553098e+103
 8.11130831e+103 1.11033632e+104 1.51991108e+104 2.08056754e+104
 2.84803587e+104 3.89860370e+104 5.33669923e+104 7.30527154e+104
 1.00000000e+105]


In [37]:
func = np.fromfunction(lambda i, j: i != j, (5, 3), dtype=int)
print(func)

[[False  True  True]
 [ True False  True]
 [ True  True False]
 [ True  True  True]
 [ True  True  True]]


In [10]:
a = np.arange(25).reshape(5,5)
b = np.arange(15).reshape(5,3)
print("{}\n{}\n{}".format(a,"-"*20,b))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
--------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [11]:
print("Scalar Multiplication: \n", a*3)

Scalar Multiplication: 
 [[ 0  3  6  9 12]
 [15 18 21 24 27]
 [30 33 36 39 42]
 [45 48 51 54 57]
 [60 63 66 69 72]]


In [12]:
print("Addition: \n", b+b)

Addition: 
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]]


In [13]:
print("Squared = \n", a**2)

Squared = 
 [[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


In [14]:
print("b * b = \n", b*b)

b * b = 
 [[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]
 [144 169 196]]


In [15]:
#Matrix multipliction
a@b

array([[ 90, 100, 110],
       [240, 275, 310],
       [390, 450, 510],
       [540, 625, 710],
       [690, 800, 910]])

In [16]:
print("{}\nRow: {}\nColumn: {}\nTotal: {}\nMax: {}\nMin: {}".format(a, a.sum(axis=1), a.sum(axis=0), a.sum(), a.max(), a.min()))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Row: [ 10  35  60  85 110]
Column: [50 55 60 65 70]
Total: 300
Max: 24
Min: 0


In [17]:
b = (a*np.pi)*2
print(b)

[[  0.           6.28318531  12.56637061  18.84955592  25.13274123]
 [ 31.41592654  37.69911184  43.98229715  50.26548246  56.54866776]
 [ 62.83185307  69.11503838  75.39822369  81.68140899  87.9645943 ]
 [ 94.24777961 100.53096491 106.81415022 113.09733553 119.38052084]
 [125.66370614 131.94689145 138.23007676 144.51326207 150.79644737]]


In [18]:
d = np.sin(b)
print("Sine: \n",d)

Sine: 
 [[ 0.00000000e+00 -2.44929360e-16 -4.89858720e-16 -7.34788079e-16
  -9.79717439e-16]
 [-1.22464680e-15 -1.46957616e-15 -1.71450552e-15 -1.95943488e-15
  -2.20436424e-15]
 [-2.44929360e-15 -9.79965032e-15 -2.93915232e-15  3.92134568e-15
  -3.42901104e-15]
 [-1.07793678e-14 -3.91886976e-15  2.94162824e-15 -4.40872848e-15
  -1.17590852e-14]
 [-4.89858720e-15  1.96191080e-15 -1.95993006e-14 -1.27388026e-14
  -5.87830464e-15]]


In [19]:
c = np.cos(b)
print("Cosine: \n",c)

Cosine: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
a = np.arange(20)

In [21]:
#Indexing and slicing works similar to Lists
a[3]

3

In [22]:
a[5:9]

array([5, 6, 7, 8])

In [23]:
a[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
b

array([[  0.        ,   6.28318531,  12.56637061,  18.84955592,
         25.13274123],
       [ 31.41592654,  37.69911184,  43.98229715,  50.26548246,
         56.54866776],
       [ 62.83185307,  69.11503838,  75.39822369,  81.68140899,
         87.9645943 ],
       [ 94.24777961, 100.53096491, 106.81415022, 113.09733553,
        119.38052084],
       [125.66370614, 131.94689145, 138.23007676, 144.51326207,
        150.79644737]])

In [25]:
b[:3,1]

array([ 6.28318531, 37.69911184, 69.11503838])

In [26]:
b[3,0]

94.24777960769379

In [27]:
b[1:4,0:2]

array([[ 31.41592654,  37.69911184],
       [ 62.83185307,  69.11503838],
       [ 94.24777961, 100.53096491]])

In [28]:
#Convert to 1D array
b = b.flatten()
print(b)

[  0.           6.28318531  12.56637061  18.84955592  25.13274123
  31.41592654  37.69911184  43.98229715  50.26548246  56.54866776
  62.83185307  69.11503838  75.39822369  81.68140899  87.9645943
  94.24777961 100.53096491 106.81415022 113.09733553 119.38052084
 125.66370614 131.94689145 138.23007676 144.51326207 150.79644737]


In [29]:
#Iteration
for item in b:
    print(item)

0.0
6.283185307179586
12.566370614359172
18.84955592153876
25.132741228718345
31.41592653589793
37.69911184307752
43.982297150257104
50.26548245743669
56.548667764616276
62.83185307179586
69.11503837897544
75.39822368615503
81.68140899333463
87.96459430051421
94.24777960769379
100.53096491487338
106.81415022205297
113.09733552923255
119.38052083641213
125.66370614359172
131.94689145077132
138.23007675795088
144.51326206513048
150.79644737231007


In [30]:
for item in b.flat:
    print(item)

0.0
6.283185307179586
12.566370614359172
18.84955592153876
25.132741228718345
31.41592653589793
37.69911184307752
43.982297150257104
50.26548245743669
56.548667764616276
62.83185307179586
69.11503837897544
75.39822368615503
81.68140899333463
87.96459430051421
94.24777960769379
100.53096491487338
106.81415022205297
113.09733552923255
119.38052083641213
125.66370614359172
131.94689145077132
138.23007675795088
144.51326206513048
150.79644737231007


In [31]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
#b references the same memory location as a
b = a
b is a

True

In [33]:
#Changes done to b will reflect in a and vise versa
b.shape = (5, 3)
print(b.shape," ",a.shape)

(5, 3)   (5, 3)


In [34]:
#Holds the same items but can have different properties
a = np.arange(6)
b = a[:]
a.shape = (3,2)
print("Properties: \n",a,"\n\n",b)

b[4] = 10000
print("\nItems: \n",a,"\n\n",b)

Properties: 
 [[0 1]
 [2 3]
 [4 5]] 

 [0 1 2 3 4 5]

Items: 
 [[    0     1]
 [    2     3]
 [10000     5]] 

 [    0     1     2     3 10000     5]


In [35]:
b = a.copy()
b = b.flatten()
print(a,"\n\n",b)

[[    0     1]
 [    2     3]
 [10000     5]] 

 [    0     1     2     3 10000     5]
